### ISSUE TITLE
Is a C# port feasible?

### ISSUE THREAD

**Issue by midiway** [antlr/codebuff#35]
Does this lib has any crazy dependency other than ANTLR?
If no I am considering making a line-by-line port to C#.

**Comment by KvanTTT** [comment]
Please talk with @kaby76. It seems that he was developing codebuff C# port based on https://github.com/antlr/antlr4/issues/1634 issue (the first line).

**Comment by kaby76** [comment]
Yes, I did a C# port of Codebuf, and it's part of my AntlrVSIX extension for Visual Studio, in https://github.com/kaby76/AntlrVSIX/tree/master/org.antlr.codebuff. I can't say it's correct, but it does seem to work for a few tests. The code was ported using the Tangible Software Solutions Java to C# converter, with further hand changes, taking approximately a week. The main reason I wanted the port of Codebuf was to find out how it works, and to add it to my VS extension. Note, it's difficult to compare the data structures betweeen Java and C# in a side-by-side comparison because the Java and C# parsers. I'm not sure I agree with all the weights in the kNN distances for the feature vector. Formatting Antlr4 grammars, it seems like Codebuf should match lexerRuleSpec's in different contexts, but it doesn't; until I completed a corpus of exemplars that enumerated all contexts of lexerRuleSpec, it produced some strange formatting. --Ken Domino

**Comment by parrt** [comment]
Yeah, it ain't great at antlr grammars; need more work on that feature list. Also next step is to use a random forest. I built one for another project that works well and is not part of some huge library. [AniML](https://github.com/parrt/AniML).
